### PR TITLE
notification timeout fix + block users from disabling reboot, security preview, and failure notifications

### LINKED ISSUE #117: Reboot notification disappears after 3 days
The reboot notification sent after an update installs disappears from the notification shade after 3 days if the device is not rebooted in that timeframe. This creates confusion for users who do not reboot in a timely manner, which is exacerbated by the "Check for updates" button being a no-op after an update has been installed.

This seems to be caused by a feature controlled by the [all_notifs_need_ttl](https://github.com/GrapheneOS/platform_build_release/blob/16/aconfig/bp2a/com.android.server.notification/all_notifs_need_ttl_flag_values.textproto) flag, which has been enabled since Android 15 QPR1. It applies a default [3 day](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/notification/NotificationManagerService.java;drc=447eaeb3ce716b7d23c3c576e1910281a281124e;l=618) timeout to any notification not [specifying otherwise](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/notification/NotificationManagerService.java;drc=447eaeb3ce716b7d23c3c576e1910281a281124e;l=8426), except for notifications associated with a [foreground service or user-initiated job](https://cs.android.com/android/platform/superproject/main/+/main:frameworks/base/services/core/java/com/android/server/notification/NotificationManagerService.java;drc=447eaeb3ce716b7d23c3c576e1910281a281124e;l=1890).

Suppressing this behavior can be done by simply setting the timeout to -1 via [setTimeoutAfter()](https://developer.android.com/reference/android/app/Notification.Builder#setTimeoutAfter(long)), although this doesn't seem documented so it might change in the future. I've verified that this did allow a notification sent from a regular user app to persist longer than 3 days. It should just be a simple one line fix.

Nevertheless, the "Check for updates" button should still provide some feedback to the user after an update has been installed, preferably in the app itself, so having #102 merged would still be beneficial.

### PR DESCRIPTION
**Pull request by inthewaves**
### prevent reboot + security preview notifications from timing out

Closes #117

### block users from disabling the reboot and security preview notifications

This reverts commit 5fa7f8279c826c68f71c4bad356b681f4508e427. Conflicts are resolved, and the new security preview notification is marked as non-blockable.

Tested that turning the reboot notification off will result in it enabled (and unblockable) upon update.
All other notification settings besides security preview and reboot notifications preserve their settings
after update.

There is a case where I can reproduce the original issue of all the `NotificationChannel`s being
unblockable by doing the following:

- Revert the "refactor notification handling" commit, and
- Setting up conditions in Updater that would prevent a periodic update check after reboot

I reverted the refactor commit to try to reproduce the issue using the old behavior where the
`NotificationChannel` creation is done in the `onCreate` method of the `Service`. After the revert,
the new `NotificationChannel#setBlockable` calls wouldn't be active until a periodic or forced
update check happens (i.e. a `Service` is created)

This can happen quite easily, e.g.,

1. Someone can set it to require charging for periodic update checks
2. Then after update finishes, during the reboot, they unplug from charger (and maybe leave their
house)
3. With the new Updater version, the fixed notification permission will make all channels
unblockable by default
4. A periodic check or a forced update check from the Updater settings is now required for the
`setBlockable(true)` calls to come into effect from the `Service`'s `onCreate` (one-time thing) to
opt in certain channels to being blockable.
5. Periodic check doesn't happen because phone is not charging, so notification channels remain
unblockable until they charge phone + have internet for the `Service` to run again
6. If they don't plug in their phone for a long time (not uncommon behavior), a user might've
noticed this issue of all channels being unblockable and reported it

Theoretically this bug, or at least this specific case of the bug, is fixed by the
"refactor notification handling" commit. `NotificationChannel`s would always be created (and thus
updated with the new `setBlockable` calls) on `Application `start instead of being limited to the
`Service#onCreate`.  The `Service` can be delayed for many reasons, so it's not an ideal place to
put `NotificationChannel` code.

It's unknown if there are other cases where all the channels become unblockable.

### CODE REVIEW

File: src/app/seamlessupdate/client/NotificationHandler.java [hunk 1]
```diff
@@ -54,26 +54,33 @@ static void createNotificationChannels(Context context) {
...
+        final NotificationChannel progress = new NotificationChannel(NOTIFICATION_CHANNEL_ID_PROGRESS,
+                context.getString(R.string.notification_channel_progress), IMPORTANCE_LOW);
+        progress.setBlockable(true);
+        channels.add(progress);
 
         final NotificationChannel reboot = new NotificationChannel(NOTIFICATION_CHANNEL_ID_REBOOT,
                 context.getString(R.string.notification_channel_reboot), IMPORTANCE_HIGH);
         reboot.enableLights(true);
         reboot.enableVibration(true);
+        reboot.setBlockable(false);
```
Comment (muhomorr) [inline src/app/seamlessupdate/client/NotificationHandler.java]: All channels are non-blockable by default for apps with `fixed` POST_NOTIFICATIONS permission. Same applies to `setSecurityPreview.setBlockable(false)` below.

File: src/app/seamlessupdate/client/NotificationHandler.java [hunk 2]
```diff
@@ -54,26 +54,33 @@ static void createNotificationChannels(Context context) {
...
         channels.add(reboot);
 
-        channels.add(new NotificationChannel(NOTIFICATION_CHANNEL_ID_FAILURE,
-                context.getString(R.string.notification_channel_failure), IMPORTANCE_LOW));
+        final NotificationChannel failure = new NotificationChannel(NOTIFICATION_CHANNEL_ID_FAILURE,
+                context.getString(R.string.notification_channel_failure), IMPORTANCE_LOW);
+        failure.setBlockable(true);
```
Comment (muhomorr) [inline src/app/seamlessupdate/client/NotificationHandler.java]: I think it would make sense to not allow blocking the failure notifications. It's easy to accidentally do that and then never receive update failure notifications, which are important.

**Review by muhomorr — CHANGES_REQUESTED** [review]

File: src/app/seamlessupdate/client/NotificationHandler.java (hunk 2 above)
Comment (inthewaves) [reply src/app/seamlessupdate/client/NotificationHandler.java]: Done, though it seems to leave it fixed at IMPORTANCE_LOW and doesn't let use change it
